git:
  overrideGpg: true
  paging:
    colorArg: always
    useConfig: true

# from : https://github.com/mohseenrm/lazygit-tokyonight/blob/main/tokyonight/night.yaml

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#4fd6be"
      - bold
    inactiveBorderColor:
      - "#394b70"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#fca7ea"
    cherryPickedCommitBgColor:
      - "#ff007c"
    cherryPickedCommitFgColor:
      - "#65bcff"
    unstagedChangesColor:
      - "#ff757f"
    defaultFgColor:
      - "#c8d3f5"
    searchingActiveBorderColor:
      - "#ffc777"

  authorColors:
    "*": "#86e1fc"
