git:
  overrideGpg: true
  paging:
    colorArg: always
    useConfig: true

# https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_night.conf
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#4fd6be"
      - bold
    inactiveBorderColor:
      - "#394b70"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#fca7ea"
    cherryPickedCommitBgColor:
      - "#ff007c"
    cherryPickedCommitFgColor:
      - "#65bcff"
    unstagedChangesColor:
      - "#ff757f"
    defaultFgColor:
      - "#c8d3f5"
    searchingActiveBorderColor:
      - "#ffc777"

  authorColors:
    "*": "#86e1fc"

