import = [
  "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }
bold = { style = "Medium" }
size = 14

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.80
blur = true

[keyboard]
bindings = [
  # jump word
  { key = "Right", mods = "Option", chars = "\u001BF" },
  { key = "Left",  mods = "Option", chars = "\u001BB" },
  # jump line
  { key = "Left",  mods = "Command", chars = "\u001bOH"  },
  { key = "Right", mods = "Command", chars =  "\u001bOF" },
  # delete line
  { key = "Back",  mods = "Command", chars = "\u0015"    },
  # test autocommit
]
